-- ==============================================================================
-- SUPABASE MIGRATION - SYSTEM MIGRATION (NATTO)
-- ==============================================================================

-- ── SCHEMA CREATION ──

-- Table: public.residuos
DROP TABLE IF EXISTS public.residuos CASCADE;
CREATE TABLE public.residuos (
  id bigint generated by default as identity primary key,
  unidade text not null,
  data date not null,
  tipo text not null,
  mtr text,
  classe_i numeric default 0,
  classe_ii numeric default 0,
  aterro numeric default 0,
  reciclagem numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: public.condicionantes
DROP TABLE IF EXISTS public.condicionantes CASCADE;
CREATE TABLE public.condicionantes (
  id bigint generated by default as identity primary key,
  unidade text not null,
  num text not null,
  descricao text not null,
  prazos jsonb default '[]'::jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table: public.licencas
DROP TABLE IF EXISTS public.licencas CASCADE;
CREATE TABLE public.licencas (
  id bigint generated by default as identity primary key,
  unidade text not null,
  nome text not null,
  emissao date,
  validade date,
  codigo text,
  orgao text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ── ROW LEVEL SECURITY (RLS) POLICIES ──

-- Enable RLS for all tables
ALTER TABLE public.residuos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.condicionantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.licencas ENABLE ROW LEVEL SECURITY;

-- Allow public anonymous access (SELECT, INSERT, UPDATE, DELETE) for all tables
CREATE POLICY "Leitura pública" ON public.residuos FOR SELECT USING (true);
CREATE POLICY "Inserção pública" ON public.residuos FOR INSERT WITH CHECK (true);
CREATE POLICY "Edição pública" ON public.residuos FOR UPDATE USING (true);
CREATE POLICY "Exclusão pública" ON public.residuos FOR DELETE USING (true);

CREATE POLICY "Leitura pública" ON public.condicionantes FOR SELECT USING (true);
CREATE POLICY "Inserção pública" ON public.condicionantes FOR INSERT WITH CHECK (true);
CREATE POLICY "Edição pública" ON public.condicionantes FOR UPDATE USING (true);
CREATE POLICY "Exclusão pública" ON public.condicionantes FOR DELETE USING (true);

CREATE POLICY "Leitura pública" ON public.licencas FOR SELECT USING (true);
CREATE POLICY "Inserção pública" ON public.licencas FOR INSERT WITH CHECK (true);
CREATE POLICY "Edição pública" ON public.licencas FOR UPDATE USING (true);
CREATE POLICY "Exclusão pública" ON public.licencas FOR DELETE USING (true);

